CREATE TABLE projects (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    technologies VARCHAR(500) NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    progress_pct INT NOT NULL DEFAULT 0,
    status ENUM('PLANNING','IN_PROGRESS','ON_HOLD','COMPLETED','ARCHIVED') NOT NULL DEFAULT 'PLANNING',
    github_link VARCHAR(500) NULL,
    live_link VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
